version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-saas-lab1"
s3_bucket = "sam-bootstrap-bucket-23da8b4d-8178-4643-bc97-38a86157f9f6"
s3_prefix = "serverless-saas-lab1"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
cached="true"
parallel="true"
