version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-saas-lab1"
s3_bucket = "sam-bootstrap-bucket-81e7bfae-426a-41e8-bff9-51a985f8a45e"
s3_prefix = "serverless-saas-lab1"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
cached="true"
parallel="true"
